- name: Ping dynamic inventory
  hosts: ubuntu
  become: yes

  tasks : 
  - name: updating apt
    command : sudo apt-get update

  - name : Install Docker
    command : sudo apt-get install -y docker.io
    become : yes
    become_user : root

  - name : Start Docker Service
    command : sudo systemctl start docker
    become : yes
    become_user : root

  - name: Check if container is already running
    docker_container_info:
      name: challagondlaanilkumar/insureme:latest
    register: container_info

  - name: Stop and remove the existing container (if running)
    docker_container:
      name: challagondlaanilkumar/insureme:latest
      state: stopped
    docker_container:
      name: challagondlaanilkumar/insureme:latest
      state: absent
    when: container_info.state == "running"
    delegate_to: localhost 

  - name: Deploy Docker Container
    command: docker run -d --name insureme -p 8080:8080 challagondlaanilkumar/insureme:latest