- name: Ping dynamic inventory
  hosts: ubuntu
  become: yes

  tasks:
  - name: Package update
    apt:
      update_cache: yes

  - name: Install java
    apt:
      name: openjdk-17-jdk
      state: present

  - name: Download tomcat server packages
    get_url:
      url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.19/bin/apache-tomcat-10.1.19.tar.gz
      dest: /home/ubuntu

  - name: Extract tomcat tar file
    unarchive:
      src: /home/ubuntu/apache-tomcat-10.1.19.tar.gz
      dest: /home/ubuntu
      remote_src: true
  
  - name: Delete content & directory
    ansible.builtin.file:
      state: absent
      path: /home/ubuntu/apache-tomcat-10.1.19.tar.gz
    
  - name: Starting Tomact Service ....
    shell: nohup /home/ubuntu/apache-tomcat-10.1.19/bin/startup.sh

  - name: Copy Tomcat service from local to remote
    copy:
       src: tomcat.service
       dest: /etc/systemd/system/
       mode: 0755

  - name: Enable the tomcat service and start
    become: yes
    systemd:
      name: tomcat
      state: started
      enabled: true
      daemon_reload: true

  - name: Connect to Tomcat server on port 8080 and check status 200 - Try 5 times
    tags: test
    uri:
      url: http://localhost:8080
    register: result
    until: "result.status == 200"
    retries: 5
    delay: 10
        
        