- name: Ping dynamic inventory
  hosts: ubuntu
  become: yes

  tasks:
  - name: Package update
    apt:
      update_cache: yes

  - name: Install java
    apt:
      name: java
      state: present

  - name: Download tomcat server packages
    get_url:
      url: https://dlcdn.apache.org/tomcat/tomcat-10/v10.1.19/bin/apache-tomcat-10.1.19.tar.gz
      dest: /home/ubuntu

  - name: Extract tomcat tar file
    unarchive:
      src: /home/ubuntu/apache-tomcat-10.1.19.tar.gz
      dest: /home/ubuntu
      remote_src: true
    
  - name: Moving to opt directory
    command: mv /home/ubuntu/apache-tomcat-10.1.19 /home/ubuntu/opt/tomact
    args:
      creates: /home/ubuntu/opt/tomact
    
  - name: Starting Tomact Service ....
    shell: nohup /home/ubuntu/opt/tomact/bin/startup.sh

  - name: Reload the SystemD to re-read configurations
    become: yes
    systemd:
      daemon-reload: yes

  - name: Enable the tomcat service and start
    become: yes
    systemd:
      name: tomcat
      enabled: yes
      state: started

  - name: Connect to Tomcat server on port 8080 and check status 200 - Try 5 times
    tags: test
    uri:
      url: http://localhost:8080
    register: result
    until: "result.status == 200"
    retries: 5
    delay: 10

  - name: Access web server resources
    loop: "{{ ubuntu }}"  # Loop through the list
    loop_control:
      loop_var: host_ip
    uri:
      url: https://{{ host_ip }}:8080  # Use host_ip loop variable
      method: GET
        
        